HMS web/Models/Fastighet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HMS_web.Models
{
    [MetadataType(typeof(Fastighet))]
    public partial class fst_property_table
    {
    }

    public class Fastighet
    {
        public Fastighet()
        {
            created = DateTime.Now;
        }

        //public bool Error { get; set; }


        // Län
        [Display(Name="Länskod")]
        public object county_code { get; set; }
        [Display(Name = "Kommunkod")]
        public object municipal_code { get; set; }
        [Display(Name = "Församlingskod")]
        public object parish_code { get; set; }

        [Display(Name = "Län")]
        public object county_name { get; set; }
        [Display(Name = "Kommun")]
        public object municipal_name { get; set; }
        [Display(Name = "Församling")]
        public object parish_name { get; set; }

        [Display(Name = "Fastighetsnummer")]
        //[Required(ErrorMessage = "Fastighetsnummer måste fyllas i!")]
        public object prop_number { get; set; }
        [Display(Name = "Fastighetsnamn")]
        [Required(ErrorMessage = "Fastighetsnamn måste fyllas i!")]
        public object prop_name { get; set; }
        [Display(Name = "Block")]
        [Required(ErrorMessage = "Block måste fyllas i!")]
        public object block_number { get; set; }
        [Display(Name = "Enhet")]
        [Required(ErrorMessage = "Enhet måste fyllas i!")]
        public object unit_number { get; set; }
        [Display(Name = "Areal (Ha)")]
        public object areal_ha { get; set; }

        [Display(Name = "Skapad av")]
        public object created_by { get; set; }
        [Display(Name = "Skapad datum")]
        public object created { get; set; }
        [Display(Name = "Fastighetsnamn")]
        public object prop_full_name { get; set; }
    }
}

HMS web/Controllers/FastighetController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HMS_web.Models;
using HMS_web.Classes;
using System.Data.Entity.Validation;
using System.Diagnostics;

namespace HMS_web.Controllers
{
    public class PaginatedFastighet<T> : PaginatedList<T>
    {
        // filtreringsargument
        public string FastNamn;
        public /*DateTime?*/ string DatumFran;
        public /*DateTime?*/ string DatumTill;
        public string FastNummer;
        public string Agare;
        public string Inventerare;
        public string SkapadAv;
        public string OrderBy;
        public int? OrderByDesc;

        public PaginatedFastighet(IQueryable<T> source, int pageIndex, int pageSize)
            : base(source, pageIndex, pageSize)
        {
        }
    }
    
    public class FastighetController : Controller
    {
        private HMS_webEntities db = new HMS_webEntities();

        //
        // GET: /Fastighet/

        public ActionResult Index(int? Page)
        {
            const int pageSize = 10;
            string Namn = "";

            var dbFastighet = db.fst_property_table.Where(a => a.prop_name.Contains(Namn)).OrderBy(a => a.id);
            var paginatedTrakt = new PaginatedList<fst_property_table>(dbFastighet, Page ?? 0, pageSize);
            return View(paginatedTrakt);
        }

        //
        // GET: /Fastighet/Details/5

        public ActionResult Details(int id = 0)
        {
            fst_property_table fst_property_table = db.fst_property_table.Find(id);
            if (fst_property_table == null)
            {
                return HttpNotFound();
            }
            return View(fst_property_table);
        }

        //
        // GET: /Fastighet/Create

        public ActionResult Create()
        {
            return View();
        }


        //
        // POST: /Fastighet/Create

        [HttpPost]
        public ActionResult Create(fst_property_table fst_property_table)
        {
            if (ModelState.IsValid)
            {
                db.fst_property_table.Add(fst_property_table);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(fst_property_table);
        }

        //
        // GET: /Fastighet/Edit/5

        [EnhancedAuth("adminGroup")]
        public ActionResult Edit(int id = 0)
        {
            fst_property_table fst_property_table = db.fst_property_table.Find(id);
            if (fst_property_table == null)
            {
                return HttpNotFound();
            }
            return View(fst_property_table);
        }

        //
        // POST: /Fastighet/Edit/5

        [HttpPost]
        [EnhancedAuth("adminGroup")]
        public ActionResult Edit(fst_property_table fst_property_table)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fst_property_table).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(fst_property_table);
        }

        //
        // GET: /Fastighet/Delete/5

        [EnhancedAuth("adminGroup")]
        public ActionResult Delete(int id = 0)
        {
            fst_property_table fst_property_table = db.fst_property_table.Find(id);
            if (fst_property_table == null)
            {
                return HttpNotFound();
            }
            return View(fst_property_table);
        }

        //
        // POST: /Fastighet/Delete/5

        [HttpPost, ActionName("Delete")]
        [EnhancedAuth("adminGroup")]
        public ActionResult DeleteConfirmed(int id)
        {
            fst_property_table fst_property_table = db.fst_property_table.Find(id);
            db.fst_property_table.Remove(fst_property_table);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }


        //
        // GET: /Fastighet/ChooseAjax

        public ActionResult ChooseAjax(int? page, string orderBy, int? orderByDesc, string fastNamn, string fastNummer, DateTime? datumFran, DateTime? datumTill, string reset = "")
        {
            // Don't allow this method to be called directly.
            //if (this.HttpContext.Request.IsAjaxRequest() != true)
                //return RedirectToAction("Index", "Fastighet");

            const int pageSize = 10;

            if (reset == null || reset == "")
            {
                if (fastNamn == null) fastNamn = "";
                if (fastNummer == null) fastNummer = "";
                if (orderBy == null) orderBy = "";
            }
            else
            {
                ModelState.Clear();

                fastNamn = "";
                fastNummer = "";
                page = 0;
                datumFran = null;
                datumTill = null;
                orderBy = "";
            }


            IQueryable<fst_property_table> dbFastighet;
            dbFastighet = from fast in db.fst_property_table
                          //join propowner in db.fst_prop_owner_table on fast.id equals propowner.prop_id
                          //join owner in db.fst_contacts_table on propowner.contact_id equals owner.id
                          //TODO: join i linq kräver att elementen finns i bägge tabellerna! testa med group join into.
                        where
                        (fastNamn == "" || fast.prop_name.Contains(fastNamn)) &&
                        (fastNummer == "" || fast.prop_number.Contains(fastNummer)) &&
                        (datumFran == null || fast.created > datumFran) &&
                        (datumTill == null || fast.created < datumTill)
                        select fast;

            switch (orderBy)
            {
                case "trakt_prop_name":
                    if (orderByDesc == 1) dbFastighet = dbFastighet.OrderBy(a => a.prop_name);
                    else dbFastighet = dbFastighet.OrderByDescending(a => a.prop_name);
                    break;
                case "trakt_created_by":
                    if (orderByDesc == 1) dbFastighet = dbFastighet.OrderBy(a => a.prop_name);
                    else dbFastighet = dbFastighet.OrderByDescending(a => a.prop_name);
                    break;
                default:
                    if (orderByDesc == 1) dbFastighet = dbFastighet.OrderBy(a => a.prop_name);
                    else dbFastighet = dbFastighet.OrderByDescending(a => a.prop_name);
                    break;
            } 

            //var dbFastighet = db.fst_property_table.Where(a => a.prop_name.Contains(namn)).OrderBy(a => a.id);
            var paginatedFast = new PaginatedFastighet<fst_property_table>(dbFastighet, page ?? 0, pageSize);

            paginatedFast.FastNummer = fastNummer;
            paginatedFast.FastNamn = fastNamn;
            paginatedFast.DatumFran = datumFran.ToString();
            paginatedFast.DatumTill = datumTill.ToString();
            paginatedFast.OrderBy = orderBy;
            paginatedFast.OrderByDesc = orderByDesc;

            return PartialView(paginatedFast);
        }


        //
        // GET: /Fastighet/CreateAjax
        public ActionResult CreateAjax()
        {
            if (this.HttpContext.Request.IsAjaxRequest() == true)
            {
                var model = new fst_property_table();   // Fastighet();
                return PartialView("CreateAjax", model);
            }

            return View();
        }

        //
        // POST: /Fastighet/CreateAjax

        [HttpPost]
        public ActionResult CreateAjax(fst_property_table fastighet)
        {
            if (ModelState.IsValid)
            {
                // Kontrollera att inte fastighetsnummer redan finns
                var query = db.fst_property_table.Where(a => a.prop_number == fastighet.prop_number).FirstOrDefault();

                if (query != null)  // 
                {
                    ModelState.AddModelError("prop_number", "Fastighetsnummer finns redan!");
                    fastighet.id = -1; 
                    return Json(fastighet);
                }

                try {
                    //fastighet.created = DateTime.Now;
                    fastighet.created_by = User.Identity.Name;
                    fastighet.created = DateTime.Now;
                    fastighet.prop_full_name = fastighet.prop_name + " " + fastighet.block_number + ":" + fastighet.unit_number;
                    db.fst_property_table.Add(fastighet);
                    db.SaveChanges();

                    //fastighet = db.fst_property_table.OrderByDescending(a => a.id).First();

                    // save went alright
                    return Json(fastighet);
                }
                catch (DbEntityValidationException dbEx)
                {
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            Trace.TraceInformation("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                        }
                    }
                }
            }

            // something is not entered correctly
            fastighet.id = -1;
            return Json(fastighet);
        }

    }
}

HMS web/Views/Fastighet/Create.cshtml
@model HMS_web.Models.fst_property_table

@{
    ViewBag.Title = "Skapa";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>fst_property_table</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.prop_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.prop_name)
            @Html.ValidationMessageFor(model => model.prop_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.block_number)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.block_number)
            @Html.ValidationMessageFor(model => model.block_number)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.unit_number)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.unit_number)
            @Html.ValidationMessageFor(model => model.unit_number)
            
        <div class="editor-label">
            @Html.LabelFor(model => model.prop_number)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.prop_number)
            @Html.ValidationMessageFor(model => model.prop_number)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.county_code)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.county_code)
            @Html.ValidationMessageFor(model => model.county_code)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.municipal_code)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.municipal_code)
            @Html.ValidationMessageFor(model => model.municipal_code)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.parish_code)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.parish_code)
            @Html.ValidationMessageFor(model => model.parish_code)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.county_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.county_name)
            @Html.ValidationMessageFor(model => model.county_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.municipal_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.municipal_name)
            @Html.ValidationMessageFor(model => model.municipal_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.parish_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.parish_name)
            @Html.ValidationMessageFor(model => model.parish_name)
        </div>

        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.areal_ha)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.areal_ha)
            @Html.ValidationMessageFor(model => model.areal_ha)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HMS web/Views/Fastighet/CreateAjax.cshtml
@model HMS_web.Models.fst_property_table

@{
    ViewBag.Title = "Skapa";
}

@using (Html.BeginForm("CreateAjax", "Fastighet", FormMethod.Post, new { id = "createFastighetForm" }))
{
    @Html.HiddenFor(model => model.id)

        <div class="editor-label">
            @Html.LabelFor(model => model.prop_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.prop_name)
            @Html.ValidationMessageFor(model => model.prop_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.block_number)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.block_number)
            @Html.ValidationMessageFor(model => model.block_number)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.unit_number)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.unit_number)
            @Html.ValidationMessageFor(model => model.unit_number)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.prop_number)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.prop_number)
            @Html.ValidationMessageFor(model => model.prop_number)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.county_code)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.county_code)
            @Html.ValidationMessageFor(model => model.county_code)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.municipal_code)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.municipal_code)
            @Html.ValidationMessageFor(model => model.municipal_code)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.parish_code)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.parish_code)
            @Html.ValidationMessageFor(model => model.parish_code)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.county_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.county_name)
            @Html.ValidationMessageFor(model => model.county_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.municipal_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.municipal_name)
            @Html.ValidationMessageFor(model => model.municipal_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.parish_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.parish_name)
            @Html.ValidationMessageFor(model => model.parish_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.areal_ha)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.areal_ha)
            @Html.ValidationMessageFor(model => model.areal_ha)
        </div>
}

HMS web/Views/Fastighet/Delete.cshtml
@model HMS_web.Models.fst_property_table

@{
    ViewBag.Title = "Radera";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>fst_property_table</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.county_code)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.county_code)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.municipal_code)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.municipal_code)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.parish_code)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.parish_code)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.county_name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.county_name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.municipal_name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.municipal_name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.parish_name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.parish_name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.prop_number)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.prop_number)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.prop_name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.prop_name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.block_number)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.block_number)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.unit_number)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.unit_number)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.areal_ha)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.areal_ha)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.created_by)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.created_by)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.created)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.created)
    </div>

</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

HMS web/Views/Fastighet/Details.cshtml
@model HMS_web.Models.fst_property_table

@{
    ViewBag.Title = "Detaljer";
}

<h2>Detaljer</h2>
TODO: Visa lista med bestånd som hör till fastigheten

<fieldset>
    <legend>fst_property_table</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.county_code)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.county_code)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.municipal_code)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.municipal_code)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.parish_code)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.parish_code)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.county_name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.county_name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.municipal_name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.municipal_name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.parish_name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.parish_name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.prop_number)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.prop_number)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.prop_name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.prop_name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.block_number)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.block_number)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.unit_number)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.unit_number)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.areal_ha)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.areal_ha)
    </div>

</fieldset>
<p>
    @Html.ActionLink("Redigera", "Edit", new { id=Model.id }) |
    @Html.ActionLink("Tillbaka till listan", "Index")
</p>

HMS web/Views/Fastighet/Edit.cshtml
@model HMS_web.Models.fst_property_table

@{
    ViewBag.Title = "Editera";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>fst_property_table</legend>

        @Html.HiddenFor(model => model.id)

        <div class="editor-label">
            @Html.LabelFor(model => model.county_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.county_name)
            @Html.ValidationMessageFor(model => model.county_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.municipal_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.municipal_name)
            @Html.ValidationMessageFor(model => model.municipal_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.parish_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.parish_name)
            @Html.ValidationMessageFor(model => model.parish_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.prop_number)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.prop_number)
            @Html.ValidationMessageFor(model => model.prop_number)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.prop_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.prop_name)
            @Html.ValidationMessageFor(model => model.prop_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.block_number)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.block_number)
            @Html.ValidationMessageFor(model => model.block_number)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.unit_number)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.unit_number)
            @Html.ValidationMessageFor(model => model.unit_number)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.areal_ha)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.areal_ha)
            @Html.ValidationMessageFor(model => model.areal_ha)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HMS web/Views/Fastighet/Index.cshtml
@model HMS_web.Classes.PaginatedList<HMS_web.Models.fst_property_table>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Skapa ny", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ElementAt(0).prop_number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ElementAt(0).prop_full_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ElementAt(0).areal_ha)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.prop_number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prop_full_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.areal_ha)
        </td>
        <td>
            @Html.ActionLink("Redigera", "Edit", new { id=item.id, page = Model.PageIndex }) |
            @Html.ActionLink("Detaljer", "Details", new { id=item.id, page = Model.PageIndex }) |
            @Html.ActionLink("Radera", "Delete", new { id=item.id, page = Model.PageIndex })
        </td>
    </tr>
}

</table>
<div>
    <br />
    <table>
        <tr>
            <td>
                @if (Model.HasPreviousPage) {
                    @Html.ActionLink("<<Första", "Index", new { Page = 0 });
                    @Html.ActionLink("<Föregående", "Index", new { Page = (Model.PageIndex-1) });
                }
                else
                {
                    @Html.Raw("&lt;&lt;Första ")
                    @Html.Raw("&lt;Föregående")
                }
            </td>
            <td>
                <b>@Html.Raw(String.Format("(Sida {0}/{1})", Model.PageIndex+1, Model.TotalPages))</b>
            </td>            
            <td>
                @if (Model.HasNextPage)
                {
                    @Html.ActionLink("Nästa>", "Index", new { Page = (Model.PageIndex + 1) });
                    @Html.ActionLink("Sista>>", "Index", new { Page = (Model.TotalPages - 1) });
                }
                else
                {
                    @Html.Raw("Nästa&gt; ")
                    @Html.Raw("Sista&gt;&gt;")
                }
            </td>
        </tr>
    </table>
</div>