HMS web/Models/Bestand.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HMS_web.Models
{
    [MetadataType(typeof(esti_trakt_table_metadata))]
    public partial class esti_trakt_table
    {
    }

    public class esti_trakt_table_metadata
    {
        public object trakt_id { get; set; }
        public object trakt_num { get; set; }
        public object trakt_pnum { get; set; }
        //[Required(ErrorMessage = "Beståndsnamn måste fyllas i!")]
        [Display(Name = "Beståndsnamn")]
        public object trakt_name { get; set; }
        public object trakt_type { get; set; }
        [Display(Name = "Inventeringsdatum")]
        public object trakt_date { get; set; }
        public object trakt_prop_id { get; set; }
        [Display(Name = "Areal (Ha)")]
        public object trakt_areal { get; set; }
        public object trakt_areal_consider { get; set; }
        public object trakt_areal_handled { get; set; }
        [Display(Name = "Ålder")]
        public object trakt_age { get; set; }
        [Display(Name = "Ståndortsindex")]
        public object trakt_si_h100 { get; set; }
        public object trakt_withdraw { get; set; }
        public object trakt_hgt_over_sea { get; set; }
        public object trakt_ground { get; set; }
        public object trakt_surface { get; set; }
        public object trakt_rake { get; set; }
        public object trakt_mapdata { get; set; }
        public object trakt_latitude { get; set; }
        public object trakt_longitude { get; set; }
        public object trakt_x_coord { get; set; }
        public object trakt_y_coord { get; set; }
        public object trakt_origin { get; set; }
        public object trakt_inp_method { get; set; }
        public object trakt_hgt_class { get; set; }
        public object trakt_cut_class { get; set; }
        public object trakt_sim_data { get; set; }
        public object trakt_near_coast { get; set; }
        public object trakt_southeast { get; set; }
        public object trakt_region5 { get; set; }
        public object trakt_part_of_plot { get; set; }
        [Display(Name = "SI")]
        public object trakt_si_h100_pine { get; set; }
        [Display(Name = "Fastighetsnr.")]
        public object trakt_prop_num { get; set; }
        [Display(Name = "Fastighet")]
        public object trakt_prop_name { get; set; }
        [DataType(DataType.MultilineText)]
        [Display(Name = "Anteckningar")]
        public object trakt_notes { get; set; }
        [Display(Name = "Skapad av")]
        public object trakt_created_by { get; set; }
        [Display(Name = "Datum skapad")]
        public object created { get; set; }
        public object trakt_wside { get; set; }
        public object trakt_img { get; set; }
        public object trakt_areal_factor { get; set; }
        public object trakt_hgtcurve { get; set; }
        public object trakt_coordinates { get; set; }
        public object trakt_for_stand_only { get; set; }
        public object trakt_point { get; set; }
        [Display(Name = "Diarienummer")]
        public object trakt_web_diarienr { get; set; }
        [Required(ErrorMessage = "Beståndsnamn måste fyllas i!")]
        [Display(Name = "Beståndsnamn")]
        public object trakt_web_bestandsnamn { get; set; }
    }


    public class InvFil
    {
        public string Filnamn { get; set; }
        public string LagratFilnamn { get; set; }
        private string Data { get; set; }

        public InvFil(string filnamn, string lagratFilnamn)
        {
            Filnamn = filnamn;
            LagratFilnamn = lagratFilnamn;

            //m_Data = FileContentResult.Open();
        }
    }

    public class Bestand
    {
        public Bestand()
        {
            Datum = DateTime.Now;

            InvFiler = new List<InvFil>();
        }

        public int BestandId { get; set; }
        public DateTime Datum { get; set; }
        public string Skapare { get; set; }

        [Required(ErrorMessage = "Minst en inventeringsfil måste väljas!")]
        [Display(Name = "Inventeringsfiler")]
        public string InvFil { get; set; }
        [Display(Name = "Inventeringsfiler")]
        public List<InvFil> InvFiler { get; set; }

        [Required(ErrorMessage = "Beståndsmall måste väljas!")]
        [Display(Name = "Beståndsmall")]
        public int BestandsmallId { get; set; }
        public IEnumerable<SelectListItem> BestandsmallList { get; set; }

        [Required(ErrorMessage = "Minst en inventerare måste väljas!")]
        [Display(Name = "Inventerare")]
        public List<int> InventerareIdList { get; set; }
        public IEnumerable<SelectListItem> InventerareList { get; set; }

        [Required(ErrorMessage = "Beståndsnamn måste fyllas i!")]
        [Display(Name = "Beståndsnamn")]
        public string Namn { get; set; }

        [Required(ErrorMessage = "Diarienummer måste fyllas i!")]
        [Display(Name = "Diarienummer")]
        public string DiarieNr { get; set; }

        [Display(Name = "Fastighetsnamn")]
        public string FastighetsNamn { get; set; }
        public int FastighetsId { get; set; }

        [Display(Name = "Fastighetsägare")]
        public string FastighetsAgare { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Anteckningar")]
        public string Anteckningar { get; set; }
    }

    public class BestandStamplingslangdViewModel
    {
        public esti_trakt_table trakt { get; set; }
        public Stamplingslangd stmpl { get; set; }
    }   
}

HMS web/Controllers/BestandController.cs
using HMS_web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using HMS_web.Classes;
using System.IO;
using System.Xml.Linq;
using System.Data.Entity.Validation;
using System.Data.Entity;
using System.Diagnostics;
using CrystalDecisions.CrystalReports.Engine;
using System.ComponentModel;
using System.Reflection;
using CrystalDecisions.Shared;
using System.Configuration;
using HMS_web.Infrastructure;

namespace HMS_web.Controllers
{
    public class PaginatedBestand<T> : PaginatedList<T>
    {
        // filtreringsargument
        public string Namn;
        public string Diarienr;
        public /*DateTime?*/ string DatumFran;
        public /*DateTime?*/ string DatumTill;
        public string Fastighet;
        public string Agare;
        public string Inventerare;
        public string SkapadAv;
        public string OrderBy;
        public int? OrderByDesc;
        public string DatumInvFran;
        public string DatumInvTill;

        public PaginatedBestand(IQueryable<T> source, int pageIndex, int pageSize) : base(source, pageIndex, pageSize)
        {
        }
    }

    public class BestandController : Controller
    {
        HMS_webEntities hmsDB = new HMS_webEntities();
        private static Rotpost rp = new Rotpost();

        //
        // GET: /Bestand/

        public ActionResult Index()
        {
            return View();
        }
        
        //
        // GET: /Bestand/Search

        public ActionResult Search(int? page, string namn, string diarienr, DateTime? datumFran, DateTime? datumTill, string orderBy, int? orderByDesc, string fastighet, string agare, string inventerare, string skapadAv, DateTime? datumInvFran, DateTime? datumInvTill, string reset = "")
        {
            const int pageSize = 10;

            if (reset == null || reset == "")
            {
                if (diarienr == null) diarienr = "";
                if (namn == null) namn = "";
                if (fastighet == null) fastighet = "";
                if (orderBy == null) orderBy = "";
                if (agare == null) agare = "";
                if (inventerare == null) inventerare = "";
                if (skapadAv == null) skapadAv = "";
            }
            else
            {
                ModelState.Clear();

                page = 0;
                datumFran = null;
                datumTill = null;
                diarienr = "";
                namn = "";
                fastighet = "";
                orderBy = "";
                agare = "";
                inventerare = "";
                skapadAv = "";
                datumInvFran = null;
                datumInvTill = null;
            }


            string sInvFran = "";
            string sInvTill = "";

            if(datumInvFran != null)
                sInvFran = ((DateTime)datumInvFran).ToString("yyyy-MM-dd");
            
            if(datumInvTill != null)
                sInvTill = ((DateTime)datumInvTill).ToString("yyyy-MM-dd");

            IQueryable<esti_trakt_table> dbTrakt;
            dbTrakt = from trakt in hmsDB.esti_trakt_table
                        join property in hmsDB.fst_property_table on trakt.trakt_prop_id equals property.id
                        where
                        (namn == "" || trakt.trakt_web_bestandsnamn.Contains(namn)) &&
                        (diarienr == "" || trakt.trakt_web_diarienr.Contains(diarienr)) &&
                        (fastighet == "" || trakt.trakt_prop_name.Contains(fastighet)) &&
                        (skapadAv == "" || trakt.trakt_created_by.Contains(skapadAv)) &&
                        (datumFran == null || trakt.created > datumFran) &&
                        (datumTill == null || trakt.created < datumTill) &&
                        (datumInvFran == null || trakt.trakt_date.CompareTo(sInvFran) >= 0) &&
                        (datumInvTill == null || trakt.trakt_date.CompareTo(sInvTill) <= 0)
                      select trakt;


            switch (orderBy)
            {
                case "trakt_prop_name":
                    if (orderByDesc == 1) dbTrakt = dbTrakt.OrderBy(a => a.trakt_prop_name);
                    else dbTrakt = dbTrakt.OrderByDescending(a => a.trakt_prop_name);
                    break;
                case "trakt_created_by":
                    if (orderByDesc == 1) dbTrakt = dbTrakt.OrderBy(a => a.trakt_created_by);
                    else dbTrakt = dbTrakt.OrderByDescending(a => a.trakt_created_by);
                    break;
                case "trakt_web_diarienr":
                    if (orderByDesc == 1) dbTrakt = dbTrakt.OrderBy(a => a.trakt_web_diarienr);
                    else dbTrakt = dbTrakt.OrderByDescending(a => a.trakt_web_diarienr);
                    break;
                case "trakt_areal":
                    if (orderByDesc == 1) dbTrakt = dbTrakt.OrderBy(a => a.trakt_areal);
                    else dbTrakt = dbTrakt.OrderByDescending(a => a.trakt_areal);
                    break;
                case "trakt_date":
                    if (orderByDesc == 1) dbTrakt = dbTrakt.OrderBy(a => a.trakt_date);
                    else dbTrakt = dbTrakt.OrderByDescending(a => a.trakt_date);
                    break;
                case "created":
                    if (orderByDesc == 1) dbTrakt = dbTrakt.OrderBy(a => a.created);
                    else dbTrakt = dbTrakt.OrderByDescending(a => a.created);
                    break;
                case "trakt_name":
                default:
                    if (orderByDesc == 1) dbTrakt = dbTrakt.OrderBy(a => a.trakt_web_bestandsnamn);
                    else dbTrakt = dbTrakt.OrderByDescending(a => a.trakt_web_bestandsnamn);
                    break;
            }            
            
            var paginatedTrakt = new PaginatedBestand<esti_trakt_table>(dbTrakt, page ?? 0, pageSize);

            paginatedTrakt.Diarienr = diarienr;
            paginatedTrakt.Namn = namn;
            paginatedTrakt.Fastighet = fastighet;
            paginatedTrakt.SkapadAv = skapadAv;
            paginatedTrakt.DatumFran = datumFran.ToString();
            paginatedTrakt.DatumTill = datumTill.ToString();
            paginatedTrakt.OrderBy = orderBy;
            paginatedTrakt.OrderByDesc = orderByDesc;
            paginatedTrakt.DatumInvFran = datumInvFran.ToString();
            paginatedTrakt.DatumInvTill = datumInvTill.ToString();

            return View(paginatedTrakt);
        }


        private void getBestandsmall(Bestand model)
        {
            model.BestandsmallList = new SelectList(hmsDB.tmpl_template_table.Where(x => x.tmpl_type_of != -1), "tmpl_id", "tmpl_name");
        }

        private void getInventerare(Bestand model)
        {
            List<SelectListItem> listItems = new List<SelectListItem>();
            var queryInventerare = from i in hmsDB.web_inventerare
                                       .Where(a => model.InventerareIdList.Contains( a.inventerare_id ) )
                                       .OrderBy(a => a.inventerare_efternamn)
                                   select i;
            foreach (var i in queryInventerare)
            {
                listItems.Add(new SelectListItem
                {
                    Value = i.inventerare_id.ToString(),
                    Text = i.inventerare_efternamn + " " + i.inventerare_namn,
                    Selected = false
                });
            }
            model.InventerareList = new SelectList(listItems, "Value", "Text");
        }

        private void getFastighet(Bestand model)
        {
            /*var query = from i in hmsDB.fst_property_table
                                       .Where(a => a.id == model.FastighetsId)
                                   select i.prop_full_name.FirstOrDefault();
            if (query != null)
            {
                model.FastighetsNamn = query.First();
            }*/

/*            var query = hmsDB.fst_property_table.Where(a => a.id == model.FastighetsId).FirstOrDefault();
            if (query != null)
            {
                model.FastighetsNamn = query.First();
            }*/

            var query = hmsDB.fst_property_table.Where(a => a.id == model.FastighetsId).Select(a => a.prop_full_name);
            if (query != null)
            {
                model.FastighetsNamn = query.First();
            }
        }

        private void getTradslag(Stamplingslangd model)
        {
            List<Tradslag> listaTradslag = new List<Tradslag>();
            var query = hmsDB.esti_trakt_data_table.Where(x => x.tdata_trakt_id == model.nTraktId && x.tdata_data_type == 1).OrderBy(x => x.tdata_spc_id);
            foreach (var trslg in query)
            {
                Tradslag t = new Tradslag();
                t.nId = trslg.tdata_spc_id;
                t.sNamn = trslg.tdata_spc_name;

                listaTradslag.Add(t);
            }

            for (int i = 0; i < model.DiameterKlasser.Count(); i++ )
            {
                model.DiameterKlasser.ElementAt(i).Tradslagslista = new List<Tradslag>(listaTradslag);
            }
        }



        //
        // GET: /Bestand/Create

        public ActionResult Create()
        {
            Bestand model = new Bestand();

            // hämta ut listor
            getBestandsmall(model);
            
            model.InventerareList = new SelectList("", "Value", "Text");

            return View(model);
        }

        //
        // POST: /Bestand/Create

        [HttpPost]
        public ActionResult Create(Bestand bestand)
        {
            try
            {

HMS web/Views/Bestand/Details.cshtml
@model HMS_web.Models.esti_trakt_table

@{
    ViewBag.Title = "Detaljer";
}

@if (TempData["Error"] != null)
{
    @Html.Raw("Error: ")
    @Html.Raw(TempData["ErrorMessage"])
    <br />
}

<h2>Detaljer</h2>

<fieldset>
    <legend>esti_trakt_table</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.trakt_web_diarienr)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.trakt_web_diarienr)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.trakt_web_bestandsnamn)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.trakt_web_bestandsnamn)
    </div>
            
    <div class="display-label">
         @Html.DisplayNameFor(model => model.trakt_areal)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.trakt_areal)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.trakt_age)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.trakt_age)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.trakt_si_h100)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.trakt_si_h100)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.trakt_prop_name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.trakt_prop_name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.trakt_date)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.trakt_date)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.trakt_notes)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.trakt_notes)
    </div>

</fieldset>
<p>
    @Html.ActionLink("Rapport stämplingslängd", "Report1", "Bestand", new { id=Model.trakt_id }, new { target="_blank" }) |
    @Html.ActionLink("Rapport stämplingslängd utökad", "Report2", "Bestand", new { id=Model.trakt_id }, new { target="_blank" }) |
    @Html.ActionLink("Rapport provträd", "Report3", "Bestand", new { id=Model.trakt_id }, new { target="_blank" }) 
    <br />
    @Html.ActionLink("Rapport stämplingslängd med provträd", "Report1p", "Bestand", new { id=Model.trakt_id }, new { target="_blank" }) |
    @Html.ActionLink("Rapport stämplingslängd utökad med provträd", "Report2p", "Bestand", new { id=Model.trakt_id }, new { target="_blank" })
    <br />
    @Html.ActionLink("Redigera", "Edit", new { id=Model.trakt_id }) |
    @Html.ActionLink("Radera", "Delete", new { id = Model.trakt_id }) |
    @Html.ActionLink("Tillbaka till lista", "Search")
</p>

<div id="busyIndicator" style="display:none">
    <img id="loading" src="~/images/ajax-loader.gif" alt=""/> 
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $('#busyIndicator')
            .hide()  // hide it initially
            .ajaxStart(function () {
                $(this).show();
            })
            .ajaxStop(function () {
                $(this).hide();
            })
        ;

        $(document).ready(function () {
            $('#busyIndicator').hide();
        });
    </script>
}

HMS web/Views/Bestand/DiameterklassItem.cshtml
@model HMS_web.Models.DiameterKlass
<tr>

@{ Html.RegisterFormContextForValidation(); }
    @using (Html.BeginCollectionItem("stmpl.DiameterKlasser"))
    {
        @Html.HiddenFor(item => item.Yta, new { id = "hiddenYtaId", data_val = "false" })
        <td>
            @Html.DropDownListFor(item => item.TradslagId, new SelectList(Model.Tradslagslista.OrderBy(x => x.nId), "nId", "sNamn", Model.TradslagId), "", new { @style = "width: 107px; margin: 1px 0 6px; padding: 2px; border: 1px solid #000000; font-size: 1.0em;" })
            @Html.ValidationMessageFor(item => item.TradslagId)
        </td>
    
        <td>
            @Html.TextBoxFor(item => item.Klass, new { @style = "width: 107px; font-size: 1.0em;" })
            @Html.ValidationMessageFor(item => item.Klass)
        </td>

        <td>
            @Html.TextBoxFor(item => item.Antal, new { @style = "width: 107px; font-size: 1.0em;" })
            @Html.ValidationMessageFor(item => item.Antal)
        </td>

        <td>
            <a href="javascript:void(0);" onclick="ConfirmRemove(this);">Radera</a>
        </td>
    }
</tr>

HMS web/Views/Bestand/Edit.cshtml
@model HMS_web.Models.BestandStamplingslangdViewModel
@using HMS_web.Models
@{
    ViewBag.Title = "Redigera";
    Html.EnableClientValidation(false);
    Html.EnableUnobtrusiveJavaScript(true);
}

<link href="~/Content/themes/base/BestandEdit.css" rel="stylesheet" type="text/css" />
<div id="loading">
    <div id="loadingcontent">
        <p id="loadingspinner">
            Sparar bestånd...
        </p>
    </div>
</div>

<h2>Redigera</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "formBestandStamplingslangd", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    
    <fieldset>
        <legend>esti_trakt_table</legend>

        @if (ViewBag.Error == true)
        {
            @Html.Raw(ViewBag.ErrorMessage)
        }

        @Html.HiddenFor(model => model.trakt.trakt_id, new { id = "hiddenTraktId", data_val = "false" })
        @Html.HiddenFor(model => model.stmpl.nTraktId, new { id = "hiddenTraktId2", data_val = "false" })

        <div class="editor-label">
            @Html.LabelFor(model => model.trakt.trakt_web_diarienr)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.trakt.trakt_web_diarienr)
            @Html.ValidationMessageFor(model => model.trakt.trakt_web_diarienr)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.trakt.trakt_web_bestandsnamn)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.trakt.trakt_web_bestandsnamn)
            @Html.ValidationMessageFor(model => model.trakt.trakt_web_bestandsnamn)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.trakt.trakt_areal)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.trakt.trakt_areal)
            @Html.ValidationMessageFor(model => model.trakt.trakt_areal)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.trakt.trakt_age)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.trakt.trakt_age)
            @Html.ValidationMessageFor(model => model.trakt.trakt_age)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.trakt.trakt_si_h100) (t.ex. T20, G18)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.trakt.trakt_si_h100)
            @Html.ValidationMessageFor(model => model.trakt.trakt_si_h100)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.trakt.trakt_prop_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.trakt.trakt_prop_name)
            @Html.ValidationMessageFor(model => model.trakt.trakt_prop_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.trakt.trakt_date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.trakt.trakt_date)
            @Html.ValidationMessageFor(model => model.trakt.trakt_date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.trakt.trakt_notes)
        </div>
        <div class="editor-multiline-field">
            @Html.EditorFor(model => model.trakt.trakt_notes)
            @Html.ValidationMessageFor(model => model.trakt.trakt_notes)
        </div>
        
        
        <div class="editor-label">
            @Html.Label("Lägg till inventeringsfil(er)")
        </div>
        <div class="editor-field" id="FileUploadContainer">
            <input data-val="true" id="file0" name="InvFil" type="file" value="" />
        </div>
        <a href="javascript:void(0);" onclick="AddFileUpload();">Lägg till fil</a>

        </fieldset>


        <fieldset>
        <legend>DiameterKlasser</legend>
        <hr />
        <div>
            @Html.Label("Stämplingslängd")
                @foreach (var yta in Model.stmpl.DiameterKlasser.OrderBy(x => x.Yta).Select(x => x.Yta).Distinct())
                {
                    <table id="DiameterklassItems-@yta" class="DiameterklassItems-@yta">
                        <tr><th>@Html.Label("Yta" + yta)</th></tr>
                        <tr>
                            <th>Trädslag</th>
                            <th>Diameterklass</th>
                            <th>Antal</th>
                            <th></th>
                        </tr>
                        
                        <tbody>
                            @foreach (var dkls in Model.stmpl.DiameterKlasser.Where(x => x.Yta == yta))
                            {
                                Html.RenderPartial("DiameterklassItem", dkls);
                            }
                        </tbody>
                    </table>
                    <a class="AddDiameterKlass" href="#" data-pageid="DiameterklassItems-@yta" data-url="@Url.Content("~/Bestand/AddDiameterklassItem/")?traktId=@Model.trakt.trakt_id&ytaId=@yta">Lägg till diameterklass</a>
                }
        </div>
        </fieldset>

        <hr />

    
    
        <fieldset>
        <legend>Provtrad</legend>
        <div>
            @Html.Label("Provträd")
            @foreach (var yta in Model.trakt.esti_trakt_plot_table.OrderBy(x => x.tplot_id).Select(x => x.tplot_id).Distinct())
            {
                <table id="ProvtradItems-@yta" class="ProvtradItems-@yta" style="list-style-type: none">
                    <tr><th>@Html.Label("Yta" + yta)</th></tr>
                    <tr>
                        <th>Trädslag</th>
                        <th>Diameter (mm)</th>
                        <th>Höjd (dm)</th>
                        <th>Grönkronegräns (dm)</th>
                        <th>Ålder</th>
                        <th>Barktjocklek (mm)</th>
                    </tr>
                    <tbody>
                        @foreach (var ptrad in Model.stmpl.Provtrad.Where(x => x.Yta == yta).OrderBy(x => x.Yta))
                        {
                            Html.RenderPartial("ProvtradItem", ptrad);
                        }
                    </tbody>
                </table>
                <a class="AddProvtrad" href="#" data-pageid="ProvtradItems-@yta" data-url="@Url.Content("~/Bestand/AddProvtradItem/")?traktId=@Model.trakt.trakt_id&ytaId=@yta">Lägg till provträd</a>
            }
        </div>
        </fieldset>    
    

        <hr />


        <p>
            <input type="submit" id="submitbtn" value="Spara" />
            <input type="button" title="Avbryt" value="Avbryt" onclick="location.href='@Url.Action("Details", "Bestand", new { id = Model.trakt.trakt_id })    ';return false;" />
        </p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/file-upload.js"></script>
    <script src="~/Scripts/dialogConfirmation.js"></script>

    <script type="text/javascript">
        $(function() {
            $('.AddDiameterKlass').click(function (e) {
                e.preventDefault();

                var divUrl = $(this).attr('data-url');
                var divDest = "#" + $(this).attr('data-pageid') + " tbody:last";    /* . = klass, # = id */

                $.get(divUrl, function(data) {
                    $(divDest).append($(data));

                    var currForm = $("#formBestandStamplingslangd");
                    currForm.removeData("validator");
                    currForm.removeData("unobtrusiveValidation");
                    $.validator.unobtrusive.parse(currForm);
                    currForm.validate();
                });
            });

            $('.AddProvtrad').click(function (e) {
                e.preventDefault();

                var divUrl = $(this).attr('data-url');
                var divDest = "#" + $(this).attr('data-pageid') + " tbody:last";    /* . = klass, # = id */

                $.get(divUrl, function(data) {
                    $(divDest).append($(data));

                    var currForm = $("#formBestandStamplingslangd");
                    currForm.removeData("validator");
                    currForm.removeData("unobtrusiveValidation");
                    $.validator.unobtrusive.parse(currForm);
                    currForm.validate();
                });
            });
            $.datepicker.setDefaults(
                $.extend(
                    { 'dateFormat': 'yy-mm-dd' },
                    $.datepicker.regional['sv']
                )
            );

            $('#trakt_trakt_date').datepicker();
        });
    </script>
    <script type="text/javascript" 
            src="@Url.Content("~/Scripts/spin.min.js")">
    </script>
    <script type="text/javascript">
        $(function () {
            $("#submitbtn").click(function () {
                $("#loading").fadeIn();
                var opts = {
                    lines: 12, // The number of lines to draw
                    length: 7, // The length of each line
                    width: 4, // The line thickness
                    radius: 10, // The radius of the inner circle
                    color: '#000', // #rgb or #rrggbb
                    speed: 1, // Rounds per second
                    trail: 60, // Afterglow percentage
                    shadow: false, // Whether to render a shadow
                    hwaccel: false // Whether to use hardware acceleration
                };
                var target = document.getElementById('loadingspinner');
                var spinner = new Spinner(opts).spin(target);
            });
        });
    </script>
 }